### ISSUE TITLE
Error while saving changes to article

### ISSUE THREAD

**Issue by janzen01** [MicrosoftSTC/stcblog#78] opened 2021-05-24 17:46 UTC
![image](https://user-images.githubusercontent.com/45731360/119387018-9f7a3700-bcc8-11eb-9fdb-0f7732fd8a5c.png)
 When I saved an article, I received an error listed above

**Comment by filiptronicek** [comment] 2021-05-24 18:15
Dupe of https://github.com/MicrosoftSTC/stcblog/issues/73 :)

**Closed as completed by filiptronicek** 2021-05-24 18:15 UTC
Labels: duplicate

**Comment by filiptronicek** [comment] 2021-05-24 18:16
@janzen01 we are investigating this, but it should be considered more like a warning than an error. Everything should work fine. At least from my testing...
